"""SSAF verification suite, file 8: Connectivity Strictly Coarser Than
Compatibility via Charge Sectors (Appendix D; Props connectivity_strict
and addressability_strict).

Setup mirrored from the toy: H = H+ (+) H- (2+2), definite-charge
admissible states, Compat_E total on A(E) (weak coexistence),
R_E = same-sector relation, O(E) generated by the charge observable Q,
~E = equality of all O(E) expectations, mu_E with distinct sector weights.

Pass conditions verified:
  X1 (Prop connectivity_strict): Compat(rho*, sigma*) = 1 while
      (rho*, sigma*) is not in R_E; R_E is a proper subset of the
      compatible pairs; the Gamma_E graph has exactly two connected
      components while the compatibility graph has one.
  X2 (Prop addressability_strict): rho1 = |+,0>, rho2 = |+,1> are
      distinct admissible states with rho1 ~E rho2, so addressability is
      strictly coarser than admissibility.
  X3: the measure distinguishes the two components by weight.
"""
import numpy as np
from itertools import combinations

TOL = 1e-12

def basis_state(idx):
    v = np.zeros(4, dtype=complex); v[idx] = 1
    return np.outer(v, v.conj())

# sectors: indices 0,1 -> '+'; 2,3 -> '-'
SAMPLE = {  # definite-charge admissible sample
    "p0": (basis_state(0), '+'), "p1": (basis_state(1), '+'),
    "m0": (basis_state(2), '-'), "m1": (basis_state(3), '-'),
}
Q = np.diag([1.0, 1.0, -1.0, -1.0]).astype(complex)

def compat(a, b):       # weak coexistence: total on A(E)
    return 1

def in_R(sa, sb):       # connectivity rule: same sector
    return sa == sb

def components(names, edge):
    comp, seen = [], set()
    for n in names:
        if n in seen: continue
        stack, group = [n], set()
        while stack:
            x = stack.pop()
            if x in group: continue
            group.add(x)
            stack += [y for y in names if y not in group and edge(x, y)]
        comp.append(group); seen |= group
    return comp

def test_X1_connectivity_strict():
    rho_star, s1 = SAMPLE["p0"]; sigma_star, s2 = SAMPLE["m0"]
    assert compat(rho_star, sigma_star) == 1
    assert not in_R(s1, s2), "cross-sector pair must not be connectivity-related"
    names = list(SAMPLE)
    R_pairs = {(a, b) for a, b in combinations(names, 2)
               if in_R(SAMPLE[a][1], SAMPLE[b][1])}
    C_pairs = {(a, b) for a, b in combinations(names, 2)}
    assert R_pairs < C_pairs, "R_E must be a PROPER subset of compatible pairs"
    gamma_comp = components(names, lambda x, y: in_R(SAMPLE[x][1], SAMPLE[y][1]))
    compat_comp = components(names, lambda x, y: True)
    assert len(gamma_comp) == 2 and len(compat_comp) == 1
    print(f"X1 strict coarseness; Gamma components = {len(gamma_comp)}, "
          f"compat components = {len(compat_comp)}: PASS")

def test_X2_addressability_strict():
    rho1, _ = SAMPLE["p0"]; rho2, _ = SAMPLE["p1"]
    assert not np.allclose(rho1, rho2), "states must be distinct in A(E)"
    # ~E: equality of expectations of every element of the algebra
    # generated by {I, Q} (charge-only interface)
    for A in [np.eye(4, dtype=complex), Q, Q @ Q]:
        assert abs(np.trace(A @ rho1) - np.trace(A @ rho2)) < TOL, \
            "O(E) must not distinguish same-sector internal states"
    print("X2 distinct admissible states, identical under O(E): PASS")

def test_X3_measure_distinguishes_components():
    mu = {'+': 0.7, '-': 0.3}   # E-fixed sector weights, declared once
    assert abs(sum(mu.values()) - 1) < TOL and mu['+'] != mu['-']
    print("X3 measure assigns distinct weights to the components: PASS")

if __name__ == "__main__":
    test_X1_connectivity_strict(); test_X2_addressability_strict()
    test_X3_measure_distinguishes_components()
    print("ALL PASS: charge-sector separation verified.")
